// `aws-exports.json` is auto-generated by the amplify CLI
// and it contains metadata such as the endpoint to query.
// Unfortunately, we can't commit this to git or else
// Amplify won't override the API endpoints in future deploys!
//
// To resolve that, we store the local development information
// in this file, commit that, then as part of the build process
// we remove that local development file. It's a bit hacky, sorry!
// Alternatively, we could do some webpack magic but that would
// require us to eject from CRA.

const awsmobile = {
  aws_project_region: 'us-west-2',
  aws_cloud_logic_custom: [
    {
      name: 'resolverAPI',
      // Run `yarn backend` to boot up the API server on this port.
      endpoint: 'http://localhost:3050',
      region: 'us-west-2',
    },
  ],
}

export default awsmobile
